on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: main

name: Quint

jobs:
  changes:
    name: Detect changes
    runs-on: github-hosted-small
    permissions:
      pull-requests: read
    outputs:
      specs: ${{ steps.filter.outputs.specs }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: step-security/paths-filter@6eee183b0d2fd101d3f8ee2935c127bca14c5625 # v3.0.5
        id: filter
        with:
          filters: |
            specs:
              - 'specs/**'

  quint-typecheck:
    name: Typecheck
    needs: changes
    if: ${{ needs.changes.outputs.specs == 'true' || github.ref == 'refs/heads/main' }}
    runs-on: github-hosted-small
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - run: find specs/ -name '*.qnt' | ./scripts/quint-forall.sh typecheck

  quint-test:
    name: Test
    needs: changes
    if: ${{ needs.changes.outputs.specs == 'true' || github.ref == 'refs/heads/main' }}
    runs-on: github-hosted-large
    env:
      MAX_SAMPLES: 100
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "18"
      - run: npm install -g @informalsystems/quint
      - run: find specs/ -name '*Test.qnt' | ./scripts/quint-forall.sh test --max-samples $MAX_SAMPLES
